INSERT INTO team (id_team, name_team, surname, short, birthday, city, photo_team) VALUES (0, 'Sporting Club Bastiais', 'Le Sporting', 'SCB', 1905, 'Bastia', NULL),
(1, 'Football Club des Girondins de Bordeaux', 'Les Girondins', 'FCGB', 1881, 'Bordeaux', NULL),
(2, 'Lille Olympique Sporting Club', 'Les Dogues', 'LOSC', 1944, 'Lille', NULL),
(3, 'Olympique Lyonnais', 'Les Gones', 'OL', 1950, 'Lyon', NULL),
(4, 'Olympique de Marseille', 'Les Phocéens', 'OM', 1899, 'Marseille', NULL),
(5, 'Montpellier Hérault Sport Club', 'La Paillade', 'MHSC', 1919, 'Montpellier', NULL),
(6, 'Football Club de Nantes', 'Les Canaris', 'FCN', 1943, 'Nantes', NULL),
(7, 'Olympique Gymnaste Club de Nice', 'Les Aiglons', 'OGCN', 1904, 'Nice', NULL),
(8, 'Toulouse Football Club', 'Les Violets', 'TFC', 1970, 'Toulouse', NULL),
(9, 'Espérance Sportive Troyes Aube Champagne', 'L''''ESTAC', 'ESTAC', 1986, 'Troyes', NULL),
(10, 'En Avant de Guingamp', 'Les Rouges et Noirs', 'EAG', 1912, 'Guingamp', NULL),
(11, 'Association sportive de Monaco football club', 'Les rouges et blancs', 'ASM', 1924, 'Monaco', NULL),
(12, 'Stade de Reims', 'Les rouges et blancs', 'SR', 1931, 'Reims', NULL),
(13, 'Stade Rennais Football Club', 'Les Hermines', 'SRFC', 1901, 'Rennes', NULL),
(14, 'Association sportive de Saint-Étienne Loire', 'Les verts', 'ASSE', 1933, 'Saint-Étienne', NULL),
(15, 'Angers Sporting Club de l''''Ouest', 'Les noirs et blancs', 'SCO', 1919, 'Angers', NULL),
(16, 'Stade Malherbe Caen Calvados Basse-Normandie', 'Malherbe', 'CAE', 1913, 'Caen', NULL),
(17, 'Gazélec Football Club Ajaccio', 'I diavuli rossi', 'GFCA', 1960, 'Ajaccio', NULL),
(18, 'Football Club de Lorient Bretagne Sud', 'Les Merlus', 'FCL', 1926, 'Lorient', NULL),
(19, 'Paris Saint-Germain Football Club', 'Le PSG', 'PSG', 1904, 'Paris', NULL);